name: release

on:
  push:
    branches: [ release ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: sftp ${{ secrets.DEPLOY_HOST }}
      - run: ${{ secrets.DEPLOY_PASS }}
